version: "3.9"

services:
  postgres:
    postgres:
  image: postgres:16
  environment:
    POSTGRES_DB: tasksdb
    POSTGRES_USER: tasksuser
    POSTGRES_PASSWORD: taskspass
  volumes:
    - pgdata:/var/lib/postgresql/data
  ports:
    - "5434:5432"   


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tasks_backend
    env_file:
      - .env
    environment:
      - PORT=${PORT:-5236}
      - NODE_ENV=${NODE_ENV:-development}
      - JWT_SECRET=${JWT_SECRET:-change_me_please}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-tasksdb}
      - POSTGRES_USER=${POSTGRES_USER:-tasksuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-taskspass}
    depends_on:
      - postgres
    networks:
      - tasks-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tasks_frontend
    env_file:
      - .env
    ports:
      - "5235:5235"
    depends_on:
      - backend
    networks:
      - tasks-net

networks:
  tasks-net:

volumes:
  pgdata:
